Mod02_01/Models/CheckValidYear.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Mod02_01.Models
{
  public  class CheckValidYear : ValidationAttribute
    {
        public CheckValidYear()
        {
            ErrorMessage = "The earliest opera is Daphne ,1598.by Corsi Peri, and Rinuccini";
        }
        public override bool IsValid(object value)
        {
            
            int year = 1900;
            if (value != null)
                year = (int)value;

            if (year < 1598)
            {
                return false;
            }
            else {
                return true;
            }
        }
    }
}

Mod02_01/Models/Opera.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Mod02_01.Models
{
   public class Opera
    {
        //[DisplayName("編號")]
        [Display(Name = "編號")]
        [Required]
        public int OperaID { get; set; }
        [DisplayName("歌劇名稱")]
        [Required(ErrorMessage = "歌劇名稱不可以為空白")]
        [StringLength(200)]
        public string Title { get; set; }
        [DisplayName("年代")]
        [CheckValidYear]
        public int? Year { get; set; }
        [DisplayName("作者")]
        [Required]
        public string Composer { get; set; }

    }
}

Mod02_01/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Mod02_01.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

Mod02_01/Controllers/OperaController.cs
using Mod02_01.DAL;
using Mod02_01.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net;
using System.Data.Entity;

namespace Mod02_01.Controllers
{
    public class OperaController : Controller
    {
        // GET: Opera
        // GET: Opera/Index?operaId=111&title=xx&year=1923&composer=John
        //public ActionResult Index(Opera opera)
        //{
        //    //var test = ModelState.IsValid;
        //    //Opera o = new Opera()
        //    //{
        //    //    OperaID = opera.OperaID,
        //    //    Title = opera.Title,
        //    //    Year = opera.Year,
        //    //    Composer = opera.Composer
        //    //};

        //    return View(opera);
        //}

        // Lab2_4
        // GET: Opera/Index
        public ActionResult Index()
        {
            OperaContext context = new OperaContext();

            return View(context.Operas.ToList());
        }

        //lab3-3
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            OperaContext context = new OperaContext();
            Opera o = context.Operas.Find(id);
            if (o == null)
                return HttpNotFound();
            return View(o);
        }

        public ActionResult Create()
        {
            return View();
        }

       [HttpPost]
       public ActionResult Create(Opera opera)
        {
            if (ModelState.IsValid)
            {
                OperaContext contex = new OperaContext();
                contex.Operas.Add(opera);
                contex.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(opera);
        }

        //GET: opera/edit/1
        //GET:opera/edit?id=1
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            OperaContext context = new OperaContext();
            Opera o = context.Operas.Find(id);
            if (o == null)
                return HttpNotFound();
            return View(o);
        }

        [HttpPost]
        public ActionResult Edit(Opera opera)
        {
            if (ModelState.IsValid)
            {
                OperaContext contex = new OperaContext();
                contex.Entry(opera).State=EntityState.Modified;
                //Opera o = contex.Operas.Find(opera.OperaID);
                //o.Title = opera.Title;
                //o.Year = opera.Year;
                //o.Composer = opera.Composer;
                contex.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(opera);
        }


        //public ActionResult Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }

        //    OperaContext context = new OperaContext();
        //    Opera o = context.Operas.Find(id);
        //    if (o == null)
        //        return HttpNotFound();
        //    return View(o);
        //}

        //[HttpPost, ActionName("Delete")]
        //public ActionResult DeleteConfirmed(int id)
        //{
        //    OperaContext context = new OperaContext();
        //    Opera o = context.Operas.Find(id);
        //    context.Operas.Remove(o);
        //    context.SaveChanges();
        //    return RedirectToAction("Index");
        //}


        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            OperaContext context = new OperaContext();
            Opera o = context.Operas.Find(id);
            if (o == null)
                return HttpNotFound();
             context.Operas.Remove(o);
            context.SaveChanges();
            return RedirectToAction("Index");
        }


        public ActionResult FilterData(int number)
        {
            OperaContext context = new OperaContext();
            var query = (from o in context.Operas
                         orderby o.Year descending
                         select o).Take(number).ToList();

            return View("Index", query);
        }

        [Route("Opera/Title/{title?}")] //title? can null or title=Wozzeck
       // [Route("Opera/Title/{title=Wozzeck}")]
        public ActionResult DetailsByTitle(string title)
        {
            OperaContext context = new OperaContext();
            Opera opera = context.Operas.FirstOrDefault<Opera>(o => o.Title == title);
                if (opera == null)
            {
                return HttpNotFound();
            }
            return View("Details", opera);
        }

    }
}

Mod02_01/Views/Home/Index.cshtml
@model Mod02_01.Models.Opera

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div> 
    </div>
</body>
</html>

Mod02_01/Views/Opera/Create.cshtml
@model Mod02_01.Models.Opera

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>
    <div> 
        @using (Html.BeginForm())
        {
            <fieldset>
                <legend>New Opera</legend>
                <div>@Html.ValidationSummary()</div>
                <div>@Html.LabelFor(m=>m.Title)</div>
                <div>@Html.EditorFor(m=>m.Title) 
                     @Html.ValidationMessageFor(m=>m.Title) 
                </div>
                <div>@Html.LabelFor(m => m.Year)</div>
                <div>@Html.EditorFor(m => m.Year)
                     @Html.ValidationMessageFor(m => m.Year) 
                </div>
                <div>@Html.LabelFor(m => m.Composer)</div>
                <div>@Html.EditorFor(m => m.Composer)
                     @Html.ValidationMessageFor(m => m.Composer)                 
                </div>
                <div>
                    <input type="submit" value="New Opera" />
                </div>
            </fieldset>
        }


        <p>
            @Html.ActionLink("Back to Opera List", "Index");
        </p>
    </div>
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
</body>
</html>

Mod02_01/Views/Opera/Delete.cshtml
@model Mod02_01.Models.Opera

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <div> 
        <ul>
             <li>
                @Html.DisplayNameFor(m => m.Title);
                @Html.DisplayFor(m => m.Title);
            </li>
            <li>
                @Html.DisplayNameFor(m => m.Year);
                @Html.DisplayFor(m => m.Year);
            </li>
            <li>
                @Html.DisplayNameFor(m => m.Composer);
                @Html.DisplayFor(m => m.Composer);
            </li>
        </ul>
        <p>
            @using (Html.BeginForm())
            {
                <input type="submit" value="Delete" />
 
            }

            @Html.ActionLink("Back To List", "Index", "Opera")
        </p>
    </div>
</body>
</html>

Mod02_01/Views/Opera/Details.cshtml
@model Mod02_01.Models.Opera

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <div> 
        <ul>
            <li>
                @Html.DisplayNameFor(m => m.OperaID);
                @Html.DisplayFor(m => m.OperaID);
            </li>
            <li>
                @Html.DisplayNameFor(m => m.Title);
                @Html.DisplayFor(m => m.Title);
            </li>
            <li>
                @Html.DisplayNameFor(m => m.Year);
                @Html.DisplayFor(m => m.Year);
            </li>
            <li>
                @Html.DisplayNameFor(m => m.Composer);
                @Html.DisplayFor(m => m.Composer);
            </li>
        </ul>
        <p>
            @Html.ActionLink("Back To List","Index","Opera")
        </p>
    </div>
</body>
</html>

Mod02_01/Views/Opera/Edit.cshtml
@model Mod02_01.Models.Opera

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>
    <div>
        @using (Html.BeginForm())
        {

            <div>@Html.ValidationSummary()</div>

            @Html.HiddenFor(m => m.OperaID)
            <fieldset>
                <legend>Edit Opera</legend>
               

               
                 <div>@Html.LabelFor(m => m.Title)</div>
                <div>
                    @Html.EditorFor(m => m.Title)
                @Html.ValidationMessageFor(m => m.Title)
            </div>
            <div>@Html.LabelFor(m => m.Year)</div>
            <div>
                @Html.EditorFor(m => m.Year)
            @Html.ValidationMessageFor(m => m.Year)
        </div>
        <div>@Html.LabelFor(m => m.Composer)</div>
        <div>
            @Html.EditorFor(m => m.Composer)
        @Html.ValidationMessageFor(m => m.Composer)
    </div>
    <div>
        <input type="submit" value="Save Opera" />
    </div>
</fieldset>
        }


        <p>
            @Html.ActionLink("Back to Opera List", "Index");
        </p>
    </div>
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
</body>
</html>

Mod02_01/Views/Opera/Index.cshtml
@model IEnumerable<Mod02_01.Models.Opera>
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div> 
        <h1>OK</h1>
        @*<ul>
          @foreach (var item in  Model)
          {
            <li>@item.OperaID -@item.Composer-</li>
          }
        </ul>*@

        <table border="1">
            <tr>
                <th>@Html.DisplayNameFor(m=>m.OperaID)</th>
                <th>@Html.DisplayNameFor(m=>m.Title)</th>
                <th>@Html.DisplayNameFor(m=>m.Year)</th>
                <th>@Html.DisplayNameFor(m=>m.Composer)</th>   
                <th>Detail</th>
                <th>Edit1</th>
                <th>Delete</th>         
            </tr>
            @foreach (var aa in Model)
            {
                <tr>
                    <th>@Html.DisplayFor(mi => aa.OperaID)</th>
                    <th>@Html.DisplayFor(mi => aa.Title)</th>
                    <th>@Html.DisplayFor(mi => aa.Year)</th>
                    <th>@Html.DisplayFor(mi => aa.Composer)</th> 
                    <th>@Html.ActionLink("Detail","Details", new { id=aa.OperaID})</th>  
                    <th>@Html.ActionLink("Edit", "Edit", new { id = aa.OperaID })</th>  
                    <th>@Html.ActionLink("Delete", "Delete", new { id = aa.OperaID }, new {onclick= "return confirm('delete ok?');"})</th> 
                </tr>
               
            }
        </table>
        <p>
            @Html.ActionLink("New Opera","Create")
        </p>

        <p>
            @using (Html.BeginForm("FilterData", "Opera", FormMethod.Get))
            {
                @*<input type="text" name="number" />*@
               @Html.TextBox("number", 2, new { maxLength=20 })
                 <input type="submit" />
            }

        </p>
        
       
     </div>
</body>
</html>